//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LKT_IO.RC
//
#define IDC_PB_HELP                     9
#define IDD_NETWORK                     100
#define IDD_DEVICE                      101
#define IDD_DRVF_GET_DRVSTAT            102
#define IDD_DRVF_GET_DEVSTAT            103
#define IDD_DEVF_GET_DEVSTAT            104
#define IDD_DRVF_COMMAND                105
#define IDD_DRVF_PORT_INPUT             106
#define IDD_DRVF_PORT_OUTPUT            107
#define IDD_DRVF_PEEK                   108
#define IDD_DRVF_POKE                   109
#define IDC_CO_DPADR                    200
#define IDC_CO_PORT                     202
#define IDC_CB_SIMULATE                 203
#define IDC_CO_IRQ                      204
#define IDC_CB_CRITICAL                 205
#define IDC_CB_WATCHDOG                 207
#define IDC_RB_HOLDLASTSTATE            208
#define IDC_RB_ZEROOUTPUTS              209
#define IDC_RB_BAUDRATE_125             210
#define IDC_RB_BAUDRATE_250             211
#define IDC_RB_BAUDRATE_500             212
#define IDC_RB_INPUT_READ_COS           214
#define IDC_RB_INPUT_READ_CYCLIC        215
#define IDC_RB_HWTEST_RW                217
#define IDC_RB_HWTEST_OFF               218
#define IDC_CO_ADDRESS                  219
#define IDC_CO_LENGTH                   220
#define IDC_CO_IO_ADDRESS               220
#define IDC_E_COMMAND                   221
#define IDC_CO_IO_TYPE                  221
#define IDC_E_WBUFFER                   222
#define IDC_CO_IO_SWAP                  222
#define IDC_E_WLENGTH                   223
#define IDC_E_RBUFFER                   224
#define IDC_E_RLENGTH                   225
#define IDC_E_STATUS                    226
#define IDC_E_ADDRESS                   227
#define IDC_E_RESULT                    228
#define IDC_E_TIMEOUT                   229
#define IDC_E_DMA_LEN                   229
#define IDC_E_PCODE                     230
#define IDC_E_VALUE                     231
#define IDC_E_DDSTATUS                  232
#define IDC_E_VALUE_RX                  232
#define IDC_CO_DPR_OFFSET               301
#define IDC_E_VALUE_TX                  303
#define IDC_COMBO_TRANSFER              312
#define IDC_COMBO_INIT                  313
#define IDC_COMBO_ADDRINC               314
#define IDC_COMBO_MODE                  315
#define IDC_COMBO_DMA_CHANNEL           316
#define IDC_COMBO_DMA_ADDR              317
#define IDD_DMA_RESET                   800
#define IDD_DMA_STOP                    801
#define IDD_DMA_START                   802
#define IDD_DMA_PORT_OUTPUT             803
#define IDD_DMA_PORT_INPUT              804
#define IDD_DMA_COMMAND                 805
#define IDD_DEVICE_G                    806
#define IDD_DRVF_PORT_GALIL             807
#define IDD_DRVF_PORT_GALIL_TX          808
#define IDD_DRVF_PORT_TX                808
#define IDD_DRVF_PORT_GALIL_RX          809
#define IDD_DRVF_PORT_RX                809
#define IDS_CP_SOFTWARE_FAULT           1000
#define IDS_CP_TOO_MANY_DRIVERS         1001
#define IDS_CP_DRIVER_NOT_CONFIGURED    1002
#define IDS_CP_DEVICE_NOT_CONFIGURED    1003
#define IDS_CP_UNKNOWN_DEVICE           1004
#define IDS_CP_NO_DEVICES               1005
#define IDS_CP_NETPASS1_ERROR           1006
#define IDS_CP_UNKNOWN_ACCESS           1007
#define IDS_CP_NO_INPUTS                1008
#define IDS_CP_NO_OUTPUTS               1009
#define IDS_CP_NO_MEMORY                1010
#define IDS_CP_NETCONFIG_ID             1011
#define IDS_CP_NETCONFIG_VERS           1012
#define IDS_CP_NETCONFIG_DPADR          1013
#define IDS_CP_NETCONFIG_DPLEN          1014
#define IDS_CP_NETCONFIG_PORT           1015
#define IDS_CP_NETCONFIG_WATCHDOG       1016
#define IDS_CP_NETCONFIG_HWTEST         1017
#define IDS_CP_NETCONFIG_STOPSTATE      1018
#define IDS_CP_NETCONFIG_SIMULATE       1019
#define IDS_CP_NETCONFIG_BAUDRATE       1020
#define IDS_CP_NETCONFIG_IRQ            1021
#define IDS_CP_NETCONFIGSIZE            1022
#define IDS_CP_SAME_DPRADR              1023
#define IDS_CP_SAME_PORT                1024
#define IDS_CP_SAME_IRQ                 1025
#define IDS_CP_DEVCONFIG_NETID          1026
#define IDS_CP_DEVCONFIG_ID             1027
#define IDS_CP_DEVCONFIG_VERS           1028
#define IDS_CP_DEVCONFIG_OFFSET         1029
#define IDS_CP_DEVCONFIG_ADDRESS        1030
#define IDS_CP_DEVCONFIG_SIZE           1031
#define IDS_CP_DEVCONFIG_CRITICAL       1032
#define IDS_CP_DEVCONFIG_FILE           1033
#define IDS_CP_DEVCONFIG_TYPE           1034
#define IDS_CP_DEVCONFIG_ERR            1035
#define IDS_CP_DEVCONFIG_INVALID_PCODE  1036
#define IDS_CP_OVERLAPP                 1040
#define IDS_CP_SAME_DP_ADDRESS          1041
#define IDS_CP_SAME_DEVICE_ADDRESS      1042
#define IDS_CP_DEVCONFIGFIELD           1043
#define IDS_CP_DEVCONFIGSIZE            1050
#define IDS_CP_CANNOT_GET_DEVCONFIG     1051
#define IDS_CP_CANNOT_GET_NETCONFIG     1052
#define IDS_CP_INVALID_PORT             1053
#define IDS_CP_INVALID_DPR              1054
#define IDS_CP_INVALID_STOPSTATE        1055
#define IDS_CP_INVALID_BAUDRATE         1056
#define IDS_CP_INVALID_POINT            1057
#define IDS_CP_POINT_OUTSIDE            1058
#define IDS_CP_INVALID_IRQLEVEL         1059
#define IDS_CP_POINT_OVERLAP            1060
#define IDS_CP_CANNOT_FIND_NETWORK      1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        800
#define _APS_NEXT_COMMAND_VALUE         4000
#define _APS_NEXT_CONTROL_VALUE         305
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
